name: 'test'

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  phpunit:
    runs-on: php:8.2
    steps:
      - uses: actions/checkout@v2
      - run: |
          composer install
      - run: |
          composer run phpunit