name: 'test'

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  phpunit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2      
      - name: Install dependencies
        run: |
          composer install
      - name: Run tests
        run: |
          composer run phpunit